example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wishlist.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import register, login_user, logout_user, show_wishlist, send_wishlist_xml, send_wishlist_json, show_json_by_id, show_xml_by_id,show_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', send_wishlist_xml, name='send_wishlist_xml'),
    path('json/', send_wishlist_json, name='send_wishlist_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', show_wishlist_ajax, name='show_wishlist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

# Create your views here.
class BarangForm(forms.Form):
    nama_barang = forms.CharField(label="Nama Barang")
    harga_barang = forms.IntegerField(label="Harga Barang")
    deskripsi = forms.CharField(label="Deskripsi", widget=forms.Textarea)

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Sasha Nabila Fortuna',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    if request.method == "POST":
        form = BarangForm(request.POST)
        if form.is_valid():
            lists = BarangWishlist(nama_barang = form.cleaned_data["nama_barang"],
                        harga_barang = form.cleaned_data["harga_barang"],
                        deskripsi = form.cleaned_data["deskripsi"],)
            lists.save()
            messages.success(request, "Barang Berhasil Disimpan")
            return redirect("wishlist:show_wishlist_ajax")
    form = BarangForm()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Sasha Nabila Fortuna',
        'last_login': request.COOKIES['last_login'],
        'form': form,
    }

    return render(request, "wishlist_ajax.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')

    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def send_wishlist_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def send_wishlist_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <nav class="navbar" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-weight: bold;">Welcome to Your Wishlist, {{nama}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">{{ nama }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <h5 style="text-align: center;">Nama: </h5>
      <p style="text-align: center;">{{nama}}</p>
      <h5 style="text-align: center;">NPM: </h5>
      <p style="text-align: center;">2106632226</p>
      <table class="table table-striped">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
        {% endfor %}
    </table>
    <h6>Sesi terakhir login: {{ last_login }}</h6>
</body>
</html>

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <nav class="navbar" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-weight: bold;">Welcome to Your Wishlist, {{nama}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">{{ nama }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <h5 style="text-align: center;">Nama: </h5>
      <p style="text-align: center;">{{nama}}</p>
      <h5 style="text-align: center;">NPM: </h5>
      <p style="text-align: center;">2106632226</p>
      <table id="wishlisttable" class="table table-striped">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
        {% endfor %}
        <tbody class="table-group-divider"></tbody>
    </table>
    <h6>Sesi terakhir login: {{ last_login }}</h6>
    <h2 style="text-align: center;">Tambah Wishlist</h2>
    <form method="POST" action="">
      {% csrf_token %}
      <table>
          {{ form.as_table }}
          <tr>
              <td></td>
              <td><input class="btn btn-primary" type="submit" value="Tambah"></td>
          </tr>
      </table>
    </form>
    <script type="text/javascript">
      $.getJSON("{% url 'wishlist:send_wishlist_json' %}", function(data) {
              $(data).each(function(i, entry) {
                  $("#wishlisttable > tbody").append($("<tr>")
                      .append($("<td>").append(entry.fields.nama_barang))
                      .append($("<td>").append(entry.fields.harga_barang))
                      .append($("<td>").append(entry.fields.deskripsi)));
              })
              })
  
      .done(function(){
          console.log("data loaded!");
      })
  
      .fail(function(e){
          console.log('error:');
          console.error(e);
      });

      $(document).ready(function () {
            $("form").submit(function (event) {
            var formData = {
                nama: $("#nama_barang").val(),
                harga: $("#harga_barang").val(),
                deskripsi: $("#deskripsi").val(),
            };
        
            $.ajax({
                type: "POST",
                url: "{% url 'wishlist:show_wishlist_ajax' %}",
                data: formData,
                dataType: "json",
                encode: true,
            }).done(function (data) {
                console.log(data);
            });
        
            event.preventDefault();
            });
      });
  </script>
</body>
</html>